"""add photo evidence to passenger reports

Revision ID: 8b6f94907e92
Revises: 93a5ec686ff8
Create Date: 2026-08-10 15:02:56.995834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6f94907e92'
down_revision: Union[str, Sequence[str], None] = '93a5ec686ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger_reports', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger_reports', 'photo_path')
    # ### end Alembic commands ###
