"""initial schema

Revision ID: 93a5ec686ff8
Revises: 
Create Date: 2026-08-10 05:52:06.568307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a5ec686ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('offence_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_fine_kes', sa.Float(), nullable=False),
    sa.Column('is_other', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offence_types_id'), 'offence_types', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fare_kes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('saccos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('license_status', sa.String(), nullable=True),
    sa.Column('primary_route_id', sa.String(), nullable=True),
    sa.Column('secondary_route_ids', sa.String(), nullable=True),
    sa.Column('sacco_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('application_submitted_at', sa.String(), nullable=True),
    sa.Column('doc_registration_cert', sa.String(), nullable=True),
    sa.Column('doc_road_service_license', sa.String(), nullable=True),
    sa.Column('doc_county_permit', sa.String(), nullable=True),
    sa.Column('doc_single_business_permit', sa.String(), nullable=True),
    sa.Column('doc_tax_compliance_cert', sa.String(), nullable=True),
    sa.Column('doc_letter_no_objection', sa.String(), nullable=True),
    sa.Column('doc_officials_contacts', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('director_mobility_status', sa.String(), nullable=True),
    sa.Column('director_mobility_reason', sa.Text(), nullable=True),
    sa.Column('director_mobility_decided_by', sa.String(), nullable=True),
    sa.Column('director_mobility_decided_at', sa.String(), nullable=True),
    sa.Column('chief_officer_status', sa.String(), nullable=True),
    sa.Column('chief_officer_reason', sa.Text(), nullable=True),
    sa.Column('chief_officer_decided_by', sa.String(), nullable=True),
    sa.Column('chief_officer_decided_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saccos_id'), 'saccos', ['id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('matatus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reg_number', sa.String(), nullable=False),
    sa.Column('sacco_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('terminal_segment', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_inspection', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_license', sa.String(), nullable=True),
    sa.Column('driver_phone', sa.String(), nullable=True),
    sa.Column('conductor_name', sa.String(), nullable=True),
    sa.Column('conductor_license', sa.String(), nullable=True),
    sa.Column('conductor_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matatus_id'), 'matatus', ['id'], unique=False)
    op.create_index(op.f('ix_matatus_reg_number'), 'matatus', ['reg_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('sacco_id', sa.String(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted_at', sa.String(), nullable=True),
    sa.Column('terms_signature', sa.String(), nullable=True),
    sa.Column('terms_version', sa.String(), nullable=True),
    sa.Column('enforcement_duty', sa.String(), nullable=True),
    sa.Column('assigned_zone_id', sa.String(), nullable=True),
    sa.Column('commander_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sacco_id', sa.String(), nullable=False),
    sa.Column('events', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sacco_id'], ['saccos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_id'), 'webhook_subscriptions', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matatu_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matatu_id'], ['matatus.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matatu_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('passenger_user_id', sa.String(), nullable=True),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('seat_numbers', sa.String(), nullable=False),
    sa.Column('fare_kes', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('booked_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matatu_id'], ['matatus.id'], ),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('crime_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('offence_committed', sa.String(), nullable=False),
    sa.Column('reg_number', sa.String(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('driver_license', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('fine_amount_kes', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_records_id'), 'crime_records', ['id'], unique=False)
    op.create_table('enforcement_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('reg_number', sa.String(), nullable=False),
    sa.Column('offence_type_id', sa.String(), nullable=False),
    sa.Column('offence_description', sa.String(), nullable=True),
    sa.Column('fine_amount_kes', sa.Float(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('photo_paths', sa.Text(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('arresting_officer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.String(), nullable=True),
    sa.Column('releasing_officer_id', sa.String(), nullable=True),
    sa.Column('released_at', sa.String(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('waived_reason', sa.Text(), nullable=True),
    sa.Column('waived_authorized_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arresting_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offence_type_id'], ['offence_types.id'], ),
    sa.ForeignKeyConstraint(['releasing_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enforcement_cases_case_reference'), 'enforcement_cases', ['case_reference'], unique=True)
    op.create_index(op.f('ix_enforcement_cases_id'), 'enforcement_cases', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matatu_id', sa.String(), nullable=False),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('amount_kes', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('issued_at', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['matatu_id'], ['matatus.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_id'), 'fines', ['id'], unique=False)
    op.create_table('passenger_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matatu_reg_number', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reporter_user_id', sa.String(), nullable=True),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('reporter_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_reports_id'), 'passenger_reports', ['id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_passenger_reports_id'), table_name='passenger_reports')
    op.drop_table('passenger_reports')
    op.drop_index(op.f('ix_fines_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_enforcement_cases_id'), table_name='enforcement_cases')
    op.drop_index(op.f('ix_enforcement_cases_case_reference'), table_name='enforcement_cases')
    op.drop_table('enforcement_cases')
    op.drop_index(op.f('ix_crime_records_id'), table_name='crime_records')
    op.drop_table('crime_records')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_webhook_subscriptions_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_matatus_reg_number'), table_name='matatus')
    op.drop_index(op.f('ix_matatus_id'), table_name='matatus')
    op.drop_table('matatus')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_saccos_id'), table_name='saccos')
    op.drop_table('saccos')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_offence_types_id'), table_name='offence_types')
    op.drop_table('offence_types')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
