"""add photo evidence to crime records

Revision ID: 9faf7a4d8e4e
Revises: 8b6f94907e92
Create Date: 2026-08-10 15:32:35.283727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faf7a4d8e4e'
down_revision: Union[str, Sequence[str], None] = '8b6f94907e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime_records', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crime_records', 'photo_path')
    # ### end Alembic commands ###
