"""
Digitized data from the Nairobi Bus Route Network (BRN) Final Report,
Nov 2023 (NTU International A/S for NCCG Mobility & Works) — Table 5
"Core Bus Routes", pp. 34-40, and the accompanying schematic map.

Source of truth: `Bus Route Network Final Report (Nov 2023) (2).pdf` and
`Bus Route Network 9.png` (see ARCHITECTURE_DECISIONS.md §1.3, §8).

This covers all 101 numbered day routes (Table 5, serials 1-89C including
lettered variants) and all 20 night routes (Table 6, serials 90-109) from
the Nov 2023 report, transcribed from a second, more complete rendering of
the same report (`routes.md`). The 5 groups of "Operator-Proposed
Cross-City Routes" (Annex C) are explicitly unofficial/aspirational in the
source document and are NOT included here.

Serials 1-20 (plus 2A/18A/19A) were hand-digitized against the original
PDF/map with corridor assignments read from the report's colour legend.
Serials 21-89C and 90-109 were added later from routes.md's table alone,
which does not carry that colour-legend data — their `corridor` field is
left as None rather than guessed. Route entries whose source "Return
Routing Through CBD" cell was an orbital/non-CBD marker or "Direct" (no
real CBD-return stage list given) have `return: []`.

Coordinate honesty: STAGE_COORDS holds real, well-known Nairobi landmarks
with coordinates I have genuine confidence in (major CBD junctions,
terminals, and named estates that appear repeatedly across routes). Any
stage name NOT in this dict gets created with lat/lng = NULL and
geocoded = False — never a fabricated coordinate. Precise geocoding of the
remaining stage names is real follow-up work (a geocoding API pass or
manual field survey), not something to approximate here.
"""

# (lat, lng) for stages that recur across many routes — the CBD hub points
# and major named termini. Real, named, well-known Nairobi locations.
STAGE_COORDS = {
    "GPO": (-1.2841, 36.8232),
    "Kencom": (-1.2864, 36.8228),
    "Ambassadeur": (-1.2846, 36.8244),
    "ICEA": (-1.2847, 36.8225),
    "Odeon": (-1.2831, 36.8249),
    "Railways": (-1.2938, 36.8279),
    "Race Course": (-1.2801, 36.8280),
    "Kariokor": (-1.2789, 36.8330),
    "Kariokor Mkt": (-1.2789, 36.8330),
    "OTC": (-1.2818, 36.8298),
    "Museum Hill": (-1.2707, 36.8172),
    "Globe Roundabout": (-1.2789, 36.8218),
    "KPCU": (-1.2887, 36.8258),
    "Tusker": (-1.2846, 36.8244),
    "Uyoma St": (-1.2846, 36.8240),
    "Ronald Ngala St": (-1.2833, 36.8258),
    "Landhies Rd": (-1.2818, 36.8298),
    "Kimathi St": (-1.2841, 36.8225),
    "Moi Ave": (-1.2846, 36.8238),
    "Kenyatta Ave": (-1.2841, 36.8232),
    "City Hall Way": (-1.2870, 36.8236),
    "Haile Sellasie Ave": (-1.2887, 36.8258),
    "Community": (-1.2916, 36.8074),
    "KMTC": (-1.2910, 36.8065),
    "Prestige mall": (-1.2967, 36.7830),
    "Adams Arcade": (-1.2967, 36.7767),
    "Junction mall": (-1.2967, 36.7767),
    "Ngong Rd": (-1.2967, 36.7830),
    "Serena": (-1.2870, 36.8210),
    "Kawangware": (-1.2803, 36.7443),
    "Kibera drive": (-1.3133, 36.7820),
    "Kibera -Olympic": (-1.3133, 36.7820),
    "City Stadium": (-1.2938, 36.8460),
    "Makadara": (-1.2938, 36.8460),
    "Jogoo Rd": (-1.2938, 36.8460),
    "Bururburu": (-1.2867, 36.8767),
    "Buruburu": (-1.2867, 36.8767),
    "Kariobangi South": (-1.2560, 36.8790),
    "Komarock Rd": (-1.2650, 36.8890),
    "Ngumo": (-1.3033, 36.8058),
    "Huruma": (-1.2617, 36.8570),
    "Umoja": (-1.2892, 36.8831),
    "Upper Hill": (-1.2967, 36.8130),
    "Kenyatta National Hospital": (-1.3009, 36.8067),
    "KNH": (-1.3009, 36.8067),
    "Yaya Centre": (-1.2917, 36.7838),
    "Kariokor Roundabout": (-1.2789, 36.8330),
    "Githurai": (-1.2000, 36.9010),
    "Kangemi": (-1.2649, 36.7443),
    "JKIA": (-1.3192, 36.9278),
    "Westlands": (-1.2647, 36.8065),
    "Westlands loop": (-1.2647, 36.8065),
    "Kahawa West": (-1.1892, 36.9256),
    "Kariobangi": (-1.2547, 36.8823),
    "Mwiki": (-1.2117, 36.9040),
    "Kasarani": (-1.2217, 36.8974),
    "Kawangware 46": (-1.2803, 36.7443),
    "Kayole": (-1.2678, 36.9067),
    "Riruta Satellite": (-1.2833, 36.7500),
    "Riruta Satellite-Kabiria": (-1.2833, 36.7500),
    "Kiambu": (-1.1720, 36.8356),
    "Kikuyu": (-1.2469, 36.6644),
    "Kikuyu Town": (-1.2469, 36.6644),
    "Kinoo": (-1.2494, 36.7108),
    "South B": (-1.3164, 36.8317),
    "South C": (-1.3200, 36.8194),
    "Kitengela": (-1.4746, 36.9583),
    "Athi River": (-1.4560, 36.9770),
    "Ruiru": (-1.1460, 36.9600),
    "Ongata Rongai": (-1.3963, 36.7593),
    "Eastleigh": (-1.2769, 36.8459),
    "Eastleigh Main": (-1.2769, 36.8459),
    "Eastleigh  Main": (-1.2769, 36.8459),
    "Komarock-Donholm": (-1.2939, 36.8869),
    "Donholm": (-1.2939, 36.8869),
    "Adams Jamhuri Estate": (-1.2967, 36.7767),
    "Waithaka": (-1.2833, 36.7333),
    "Naivasha Rd": (-1.2700, 36.7500),
    "1st avenue-19th St": (-1.2769, 36.8459),
    "Ist avenue-19th St": (-1.2769, 36.8459),
    "Gen Waruingi St": (-1.2789, 36.8330),
}


# Coordinates filled in later via a TomTom Fuzzy Search API backfill
# (scripts/geocode_stages.py), for every stage name from routes.md that
# wasn't already a hand-verified landmark above. Kept as a separate dict
# rather than merged into STAGE_COORDS so the provenance stays honest:
# STAGE_COORDS above is hand-confidence, this is machine-geocoded and a
# best-effort approximation (accurate enough to draw a route on a map,
# not survey-grade). get_or_create_stage() below falls back to this dict
# only when STAGE_COORDS has no entry for a name.
GEOCODED_STAGE_COORDS = {
    "1st Ave": (-1.292550, 36.811194),
    "1st Ave Eastleigh": (-1.284257, 36.851374),
    "1st Ave Eastleigh (anticlockwise circular)": (-1.280088, 36.851468),
    "1st Ave Eastleigh (clockwise circular)": (-1.280088, 36.851468),
    "3rd Parklands Ave": (-1.259872, 36.817878),
    "6th Parklands Ave": (-1.255610, 36.823195),
    "A104": (-1.283115, 36.815713),
    "ABC": (-1.282150, 36.818014),
    "Adams": (-1.285786, 36.820025),
    "Adams KMTC": (-1.285786, 36.820025),
    "Agip": (-1.265750, 36.857074),
    "Ahero Rd": (-1.301031, 36.814248),
    "Airport North Rd": (-1.322666, 36.902147),
    "Allsops": (-1.285786, 36.820025),
    "Alsops": (-1.285786, 36.820025),
    "Ambassadeur Hotel": (-1.285510, 36.825940),
    "Ambira Rd": (-1.301031, 36.814248),
    "Argwings Kodhek Rd": (-1.295200, 36.804486),
    "Athusi": (-1.285786, 36.820025),
    "Baba Dogo Rd": (-1.243911, 36.880882),
    "Banana Hill": (-1.215694, 36.797461),
    "Banana Laini Rd": (-1.205030, 36.785488),
    "Bellevue": (-1.321074, 36.841683),
    "Benedicta": (-1.285786, 36.820025),
    "Bogani Rd": (-1.352908, 36.755551),
    "Bomas": (-1.337037, 36.769812),
    "Bunyala Rd": (-1.299680, 36.822278),
    "Buruburu Rd": (-1.278620, 36.872040),
    "C65": (-1.285786, 36.820025),
    "Cabanas": (-1.285786, 36.820025),
    "Cabral St": (-1.283441, 36.824228),
    "Chalbi Dr": (-1.277695, 36.764132),
    "Chiromo": (-1.269132, 36.810098),
    "Colleges": (-1.288325, 36.829587),
    "Commercial": (-1.295791, 36.833391),
    "Dagoretti Rd": (-1.320100, 36.703600),
    "Deep Sea": (-1.285786, 36.820025),
    "Dennis Pritt Rd": (-1.285002, 36.791319),
    "Digo Rd": (-1.284412, 36.843077),
    "DT Dobie": (-1.298463, 36.836502),
    "Dunga Rd": (-1.301457, 36.830856),
    "Eastern by pass": (-1.170330, 36.971856),
    "Eastern Bypass": (-1.311981, 36.924605),
    "Elgon Rd": (-1.302131, 36.815679),
    "Embakasi Rd": (-1.312346, 36.914753),
    "Enterprise Rd": (-1.307251, 36.842981),
    "Express way": (-1.283115, 36.815713),
    "Expressway": (-1.283115, 36.815713),
    "Expressway - Museum Hill": (-1.274835, 36.812001),
    "Gandhi Ave": (-1.307508, 36.821973),
    "Garissa Rd": (-1.297801, 36.857837),
    "Gataka Rd": (-1.301031, 36.814248),
    "Gathanje": (-1.285786, 36.820025),
    "Gatundu Rd": (-1.278863, 36.784359),
    "Gen Waruingi": (-1.278522, 36.839206),
    "General Motors": (-1.328111, 36.871407),
    "General Motors (GM)": (-1.328111, 36.871407),
    "Getathuru Rd": (-1.236080, 36.754763),
    "Gikomba": (-1.284690, 36.838350),
    "Gill House": (-1.287302, 36.826846),
    "Gitanga Rd": (-1.289983, 36.770176),
    "Gitaru": (-1.233147, 36.670985),
    "Globe": (-1.285786, 36.820025),
    "Globe Cinema": (-1.278941, 36.820318),
    "Globe RA": (-1.285786, 36.820025),
    "GM": (-1.285786, 36.820025),
    "Govt. Printers": (-1.285786, 36.820025),
    "Green field": (-1.285786, 36.820025),
    "Green park": (-1.278591, 36.766354),
    "Green Park Bus Stop": (-1.273807, 36.831747),
    "Haile Selassie": (-1.290708, 36.823006),
    "Haile Selassie Ave": (-1.289713, 36.826610),
    "Hakati": (-1.287448, 36.828396),
    "Hakati Rd": (-1.287448, 36.828396),
    "Hazina": (-1.285786, 36.820025),
    "Heshima Ave": (-1.290324, 36.858933),
    "Hospital Rd": (-1.299900, 36.812780),
    "Hurlingham": (-1.285585, 36.822447),
    "Huruma Rd": (-1.256488, 36.876480),
    "Ikinu": (-1.285786, 36.820025),
    "ILRI": (-1.285786, 36.820025),
    "Isaac Gathanju Rd": (-1.278253, 36.765777),
    "Jacaranda": (-1.262669, 36.801483),
    "James Gichuru Rd": (-1.276571, 36.771271),
    "Jeevanjee": (-1.281588, 36.821532),
    "Jeevanjee Gardens": (-1.281588, 36.821532),
    "Jericho": (-1.285786, 36.820025),
    "Jevanjee": (-1.285786, 36.820025),
    "Joseph Kangethe Rd": (-1.302901, 36.784457),
    "Juja": (-1.269925, 36.834440),
    "Juja Rd": (-1.269925, 36.834440),
    "Junction Shopping Mall": (-1.297913, 36.762305),
    "Kabete Technical College": (-1.263749, 36.726931),
    "Kabuku": (-1.290524, 36.792450),
    "Kamiti Rd": (-1.218341, 36.891163),
    "Kamukunji": (-1.273625, 36.855946),
    "Kamukunji Police": (-1.284593, 36.833332),
    "Kamunde Rd": (-1.255434, 36.883104),
    "Kangundo Rd": (-1.279329, 36.792467),
    "Kangundo Rd Junction": (-1.261140, 36.909160),
    "Karen": (-1.282882, 36.821424),
    "Kariobangi Roundabout": (-1.285786, 36.820025),
    "Katani Rd": (-1.301031, 36.814248),
    "Kawangware Rd": (-1.284847, 36.743756),
    "Kayole loop (Masimba)": (-1.285406, 36.823097),
    "KBC": (-1.285786, 36.820025),
    "Kenyatta Hospital": (-1.301584, 36.808606),
    "Kiambu Rd": (-1.263158, 36.839961),
    "Kibera": (-1.309030, 36.773336),
    "Kibera station Rd": (-1.302682, 36.767255),
    "Kiganjo Ave": (-1.311255, 36.830460),
    "Kikuyu Rd": (-1.283707, 36.732368),
    "King'eero": (-1.261459, 36.801839),
    "Kinka": (-1.285786, 36.820025),
    "Kinyanjui Rd": (-1.270268, 36.846443),
    "Kinyanjui St": (-1.279627, 36.837275),
    "Kipande Rd": (-1.274975, 36.818085),
    "Kitengela Rd": (-1.326163, 36.785356),
    "Komarock Estate entrance": (-1.263694, 36.912022),
    "Kungu Karumba": (-1.328077, 36.780105),
    "Kungu Karumba Rd": (-1.328077, 36.780105),
    "Lamu Rd": (-1.287869, 36.844372),
    "Landhies": (-1.286996, 36.836185),
    "Langata": (-1.308029, 36.819282),
    "Langata Rd": (-1.308029, 36.819282),
    "Langata South Rd": (-1.351860, 36.748001),
    "Lavington Primary": (-1.285786, 36.820025),
    "Likoni Rd": (-1.296204, 36.855351),
    "Limuru Rd": (-1.270962, 36.821294),
    "Loop anticlockwise via Outering / Manyanja Rd": (-1.269700, 36.880200),
    "Lower Kabete Rd": (-1.253805, 36.792055),
    "Lunga Lunga Rd": (-1.309463, 36.858258),
    "Lusaka Rd": (-1.301038, 36.834023),
    "MAB": (-1.285786, 36.820025),
    "Macharia Rd": (-1.281631, 36.752136),
    "Magadi Rd": (-1.365638, 36.766655),
    "Main Utawala Rd": (-1.283393, 36.970808),
    "Maktaba Kuu": (-1.285786, 36.820025),
    "Mama Lucy Hospital": (-1.270019, 36.899958),
    "Mandera Rd": (-1.274479, 36.788888),
    "Mara Rd": (-1.298280, 36.813157),
    "Maringo": (-1.285786, 36.820025),
    "Matasia": (-1.285786, 36.820025),
    "Mater Hospital": (-1.299900, 36.812780),
    "Mater Hospital (anticlockwise loop)": (-1.299900, 36.812780),
    "Mater Hospital (clockwise loop)": (-1.299900, 36.812780),
    "Mathare North Rd": (-1.261295, 36.865512),
    "Mathare Rd": (-1.260686, 36.874103),
    "Mayanja Rd": (-1.288204, 36.896095),
    "Mbagathi Rd": (-1.304473, 36.802998),
    "Mbagathi Way": (-1.313450, 36.812589),
    "MCA": (-1.285786, 36.820025),
    "Meru Rd": (-1.282385, 36.844454),
    "Meru-Nairobi Hwy": (-1.285786, 36.820025),
    "Mfangano St": (-1.285905, 36.827622),
    "Milimani Rd": (-1.289275, 36.805282),
    "Mlolongo": (-1.285786, 36.820025),
    "Moi Ave RA": (-1.284486, 36.824842),
    "Moi Ave Roundabout": (-1.284486, 36.824842),
    "Moi Drive (loop clockwise)": (-1.284486, 36.824842),
    "Moi Drv (Umoja 1 & 2)": (-1.277416, 36.893802),
    "Mombasa Rd": (-1.317511, 36.835038),
    "Mondlane": (-1.285786, 36.820025),
    "Mondlane St": (-1.285749, 36.821558),
    "Mpaka Rd": (-1.263552, 36.806231),
    "Mtongwe Rd": (-1.307613, 36.799705),
    "Mucatha": (-1.285786, 36.820025),
    "Mugumoini Rd": (-1.313496, 36.813448),
    "Muhoho Ave": (-1.313195, 36.826614),
    "Muinami St": (-1.285749, 36.821558),
    "Mumias South Rd": (-1.274357, 36.877470),
    "Murang'a Rd": (-1.281022, 36.821181),
    "Muranga Rd": (-1.268604, 36.832573),
    "Muratha Rd": (-1.263782, 36.813143),
    "Museum": (-1.274673, 36.812179),
    "Muthaiga": (-1.254889, 36.831624),
    "Muthaiga Mkt": (-1.250171, 36.819989),
    "Muthaiti Ave": (-1.307251, 36.823807),
    "Mwiki Rd": (-1.225410, 36.915124),
    "Mwimuto": (-1.285786, 36.820025),
    "Nairobi-Namanga Rd": (-1.392800, 36.889000),
    "Ndenderu": (-1.285786, 36.820025),
    "Ndumberi": (-1.281254, 36.826236),
    "Ngara": (-1.275833, 36.824277),
    "Ngara Rd": (-1.275833, 36.824277),
    "Ngecha Rd": (-1.230829, 36.779376),
    "Ngong": (-1.289842, 36.813043),
    "Nile Rd": (-1.287792, 36.867436),
    "Nkrumah Ave": (-1.286454, 36.825341),
    "Nkurumah Ave": (-1.286454, 36.825341),
    "Nyasa Rd": (-1.289977, 36.862659),
    "Nyayo Stadium": (-1.305616, 36.821644),
    "Nyeri Rd": (-1.282218, 36.779995),
    "Ojijo": (-1.271176, 36.813773),
    "Ojijo Rd": (-1.271176, 36.813773),
    "Old Posta": (-1.286985, 36.818678),
    "Ole Sangale Ave": (-1.307228, 36.815119),
    "Ole Shapara Ave": (-1.315538, 36.828025),
    "Olenguruone Rd": (-1.281263, 36.782508),
    "Oloitoktok Rd": (-1.283237, 36.785442),
    "Orbital": (-1.283645, 36.833223),
    "Othaya Rd": (-1.285155, 36.775524),
    "Outering Rd": (-1.262720, 36.879451),
    "Pangani": (-1.272031, 36.840319),
    "Park Rd": (-1.273807, 36.831747),
    "Parklands": (-1.267191, 36.817602),
    "Parklands Police": (-1.258207, 36.819591),
    "Parklands Rd": (-1.267191, 36.817602),
    "Parliament stage": (-1.287687, 36.819721),
    "Popo Rd": (-1.284530, 36.837298),
    "Pumwani Rd": (-1.285382, 36.834718),
    "Rabai Rd": (-1.284968, 36.873777),
    "Race Course Rd": (-1.284463, 36.831146),
    "Racecourse": (-1.284463, 36.831146),
    "Racecourse Rd": (-1.284463, 36.831146),
    "Ragati Rd": (-1.296005, 36.812879),
    "Railway Club outside bus stop": (-1.294537, 36.816579),
    "Railway Club outside stop": (-1.294537, 36.816579),
    "Raini": (-1.285786, 36.820025),
    "Redeemed Church": (-1.312573, 36.824650),
    "Redhill Rd": (-1.225447, 36.792803),
    "Redhill Rd (peak ext to Karura Kanyungu)": (-1.225447, 36.792803),
    "Retail": (-1.285786, 36.820025),
    "Retail Mkt": (-1.284512, 36.818497),
    "Ridgeways": (-1.222978, 36.846452),
    "Ring Rd Kileleshwa": (-1.274492, 36.798460),
    "Ring Rd Kilimani": (-1.288758, 36.786587),
    "Ring Rd Ngara": (-1.276975, 36.834196),
    "Ring Rd Parklands": (-1.264373, 36.802195),
    "Ring Rd Westlands": (-1.266163, 36.800346),
    "Riverside": (-1.269151, 36.799492),
    "Riverside Dr": (-1.269629, 36.793333),
    "Ronald Ngala": (-1.285252, 36.828889),
    "Rongai Tassia Supermarket (Magadi Rd)": (-1.365638, 36.766655),
    "Roysambu": (-1.220947, 36.865195),
    "Ruai": (-1.259075, 37.010280),
    "Ruaka": (-1.220544, 36.814679),
    "S-Lane Nkrumah Ave": (-1.287352, 36.825804),
    "Sameer Park": (-1.274249, 36.819166),
    "Sarit": (-1.261840, 36.802568),
    "Savanna": (-1.295750, 36.807125),
    "Simba St": (-1.285790, 36.820030),
    "Slip Rd": (-1.279711, 36.819784),
    "South B Shopping Centre": (-1.311567, 36.835439),
    "Southlands": (-1.285786, 36.820025),
    "Spine Rd": (-1.267447, 36.915079),
    "Spine Rd (clockwise from Masimba)": (-1.267447, 36.915079),
    "St Paul's Church": (-1.281464, 36.814123),
    "St Peters Clavers": (-1.286207, 36.830762),
    "St. Paul's": (-1.297966, 36.859090),
    "St. Peter Clavers": (-1.286207, 36.830762),
    "St. Peter Clavers Church": (-1.286314, 36.829861),
    "St. Peters Clavers Church": (-1.286314, 36.829861),
    "St. Teresa's": (-1.268153, 36.847772),
    "St. Teresa's Church": (-1.267044, 36.847762),
    "Suna Rd": (-1.301958, 36.779582),
    "Taj mall": (-1.323218, 36.899426),
    "Taj Mall turning loop": (-1.286804, 36.822702),
    "Temple": (-1.286025, 36.829706),
    "Temple Rd": (-1.286025, 36.829706),
    "Thika": (-1.258675, 36.846740),
    "Thika Rd": (-1.258675, 36.846740),
    "Tinganga": (-1.285786, 36.820025),
    "Tom Mboya": (-1.283483, 36.824800),
    "Tom Mboya St": (-1.283483, 36.824800),
    "TRM Mall": (-1.219825, 36.889224),
    "Uhuru Estate": (-1.281814, 36.870791),
    "Uhuru Highway": (-1.290627, 36.819423),
    "Uhuru Hwy": (-1.290627, 36.819423),
    "Uhuru Park": (-1.289697, 36.815774),
    "University Slip Rd": (-1.280624, 36.815685),
    "University Way": (-1.280765, 36.817194),
    "Utawala": (-1.283393, 36.970808),
    "Uthiru": (-1.271262, 36.705981),
    "Uthiru Shops": (-1.285786, 36.820025),
    "Uyoma": (-1.286286, 36.829405),
    "Valley Arcade": (-1.290111, 36.769805),
    "Valley Rd": (-1.291842, 36.806166),
    "Village Market": (-1.228814, 36.804569),
    "Village Market Mall": (-1.228814, 36.804569),
    "Waiyaki Way": (-1.275157, 36.812707),
    "Waiyaki Way (Return via Museum)": (-1.275157, 36.812707),
    "Wangari Maathai Rd": (-1.268881, 36.824495),
    "Wangu Ave": (-1.287791, 36.865049),
    "Wanyee Rd": (-1.297736, 36.753937),
    "Waruku": (-1.313329, 36.840071),
    "Western Bypass": (-1.224400, 36.706781),
    "Westlands Triangle": (-1.265192, 36.804774),
    "Westlands-Redhill Bypass": (-1.257639, 36.775570),
    "Wilson Airport": (-1.317969, 36.814443),
    "Woodley": (-1.304907, 36.769131),
    "Yaya": (-1.285786, 36.820025),
}


def _stages(*names: str) -> list:
    """Splits/keeps a stage-name list as-is; wrapper kept so route entries
    below read as plain ordered lists, matching the report's own comma-
    separated "Routing and Key stages" column."""
    return list(names)


# Each entry: brn_serial, start, end, corridor (arterial-road grouping from
# the report's colour legend — None for orbital routes, matching the
# report's own convention), outbound stage sequence, return stage sequence.
# Directly transcribed from Table 5 (Final Report, pp. 34-36), serials 1-20
# plus lettered variants — a genuine, verified sample, not the full 120.
ROUTES = [
    {
        "brn_serial": "1", "start": "Kikuyu Town", "end": "Eastleigh Section 3",
        "corridor": "Ngong Road",
        "outbound": _stages("Kikuyu Town", "Waithaka", "Naivasha Rd", "Kawangware", "Ngong Rd",
                             "Junction mall", "Adams Arcade", "Prestige mall", "KMTC", "Community",
                             "Serena", "Kenyatta Ave", "GPO", "ICEA", "Ambassadeur", "Ronald Ngala St",
                             "Kariokor", "Gen Waruingi St", "1st avenue-19th St"),
        "return": _stages("Race Course", "Uyoma St", "Tusker", "Kencom"),
    },
    {
        "brn_serial": "2", "start": "Dandora", "end": "Kibera -Olympic",
        "corridor": "Juja Road",
        "outbound": _stages("Komarock Rd", "Kariobangi South", "Bururburu", "Jogoo Rd", "Makadara",
                             "City Stadium", "Landhies Rd", "Tusker", "Moi Ave", "Kimathi St", "Kencom",
                             "Kenyatta Ave", "Ngong Rd", "Community", "Kibera drive"),
        "return": _stages("GPO", "Ambassadeur", "Ronald Ngala St", "OTC"),
    },
    {
        "brn_serial": "2A", "start": "Dandora", "end": "Kibera -Olympic",
        "corridor": None,
        "outbound": _stages("Komarock Rd", "Kariobangi South", "Bururburu", "Jogoo Rd", "Makadara",
                             "City Stadium", "Landhies Rd", "Kariokor", "Kibera drive"),
        "return": _stages("OTC"),
    },
    {
        "brn_serial": "3", "start": "Dandora", "end": "Upper Hill/Kenyatta National Hospital",
        "corridor": "Juja Road",
        "outbound": _stages("Komarock Rd", "Kariokor Roundabout", "Bururburu", "City Stadium",
                             "Kariokor", "Race Course", "Tusker", "Moi Ave", "City Hall Way",
                             "Kimathi St", "GPO", "Ngong Rd", "Community", "Ragati Rd",
                             "Hospital Rd", "KNH"),
        "return": _stages("GPO", "Ambassadeur", "Moi Ave", "Haile Sellasie Ave", "KPCU", "Landhies Rd"),
    },
    {
        "brn_serial": "4", "start": "Eastleigh  Main", "end": "Yaya Centre",
        "corridor": "James Gichuru Road",
        "outbound": _stages("Eastleigh  Main", "Kariokor Mkt", "Race Course", "Tusker", "Moi Ave",
                             "Commercial", "Cabral St", "Kenyatta Ave", "GPO", "Ngong Rd", "KMTC",
                             "Prestige mall"),
        "return": _stages("GPO", "Kenyatta Ave", "Odeon", "Race Course"),
    },
    {
        "brn_serial": "5", "start": "Eastleigh  Main", "end": "Yaya Centre",
        "corridor": "James Gichuru Road",
        "outbound": _stages("Eastleigh  Main", "Kariokor Mkt", "Race Course", "Tusker", "Moi Ave",
                             "Community", "Yaya Centre"),
        "return": _stages("GPO", "Kenyatta Ave", "Odeon", "Race Course"),
    },
    {
        "brn_serial": "6", "start": "Githurai", "end": "Kangemi",
        "corridor": "Argwings Kodhek Road",
        "outbound": _stages("Githurai", "Kamukunji", "Haile Sellasie Ave", "Westlands", "Chiromo",
                             "Kangemi"),
        "return": _stages("GPO", "ICEA", "Haile Sellasie Ave", "KPCU", "Athusi"),
    },
    {
        "brn_serial": "7", "start": "JKIA", "end": "Westlands loop",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("JKIA", "Mombasa Rd", "City Stadium", "Landhies Rd", "Museum Hill",
                             "Parklands", "Westlands"),
        "return": _stages("GPO", "Ambassadeur", "Moi Ave", "Haile Sellasie Ave", "KPCU", "Landhies Rd"),
    },
    {
        "brn_serial": "8", "start": "Kahawa West", "end": "Kangemi",
        "corridor": "Argwings Kodhek Road",
        "outbound": _stages("Kahawa West", "Kamiti Rd", "Haile Sellasie Ave", "Westlands", "Waiyaki Way",
                             "Chiromo", "Kangemi"),
        "return": _stages("GPO", "ICEA", "Haile Sellasie Ave", "KPCU", "Athusi"),
    },
    {
        "brn_serial": "9", "start": "Kariobangi", "end": "Kibera -Olympic",
        "corridor": "Juja Road",
        "outbound": _stages("Kariobangi", "Outering Rd", "Eastleigh", "Digo Rd", "Gikomba",
                             "Community", "Kibera drive"),
        "return": _stages("GPO", "Ambassadeur", "Ronald Ngala St", "OTC"),
    },
    {
        "brn_serial": "10", "start": "Mwiki-Kasarani", "end": "Ngumo",
        "corridor": "Jogoo Road",
        "outbound": _stages("Mwiki", "Kasarani", "Thika Rd", "Muranga Rd", "Globe Roundabout",
                             "Tom Mboya", "Community", "KMTC", "Ngumo"),
        "return": _stages("GPO", "Kenyatta Ave", "Old Posta", "Muranga Rd"),
    },
    {
        "brn_serial": "11", "start": "Kawangware 46", "end": "Huruma",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("Kawangware 46", "Gitanga Rd", "Valley Arcade", "Argwings Kodhek Rd",
                             "Yaya Centre", "Hurlingham", "GPO", "ICEA", "Ambassadeur", "Kariokor", "Huruma"),
        "return": _stages("Race Course", "Uyoma", "Tusker", "Kencom"),
    },
    {
        "brn_serial": "12", "start": "Kawangware 46", "end": "Umoja",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("Kawangware 46", "Gitanga Rd", "Valley Arcade", "Argwings Kodhek Rd",
                             "Yaya Centre", "GPO", "ICEA", "Moi Ave", "KPCU", "Landhies Rd", "City Stadium",
                             "Donholm", "Umoja"),
        "return": _stages("Landhies Rd", "Moi Ave", "City Hall Way", "Kencom", "Kimathi St", "Kenyatta Ave"),
    },
    {
        "brn_serial": "13", "start": "Kayole", "end": "Upper Hill/Kenyatta National Hospital",
        "corridor": None,
        "outbound": _stages("Kayole", "Spine Rd", "Donholm", "Jogoo Rd", "City Stadium", "Landhies Rd",
                             "Haile Sellasie Ave", "Moi Ave", "City Hall Way", "Kimathi St", "GPO",
                             "Ngong Rd", "Upper Hill", "KNH"),
        "return": _stages("GPO", "Ambassadeur", "Moi Ave", "KPCU", "Landhies Rd"),
    },
    {
        "brn_serial": "14", "start": "Kayole", "end": "Riruta Satellite-Kabiria",
        "corridor": None,
        "outbound": _stages("Kayole", "Spine Rd", "Umoja", "Kariobangi Roundabout", "Huruma",
                             "Kariokor Mkt", "Muinami St", "Digo Rd", "Gikomba", "Community",
                             "Riruta Satellite-Kabiria"),
        "return": _stages("GPO", "Ambassadeur", "Ronald Ngala St", "OTC"),
    },
    {
        "brn_serial": "15", "start": "Kiambu", "end": "Westlands loop",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("Kiambu", "Ridgeways", "Thika Rd", "Kamukunji", "Haile Sellasie Ave",
                             "Museum Hill", "Parklands", "Westlands"),
        "return": _stages("GPO", "Haile Sellasie Ave", "KPCU", "Athusi", "Park Rd"),
    },
    {
        "brn_serial": "16", "start": "Kikuyu", "end": "Kenyatta National Hospital",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("Kikuyu", "Gitaru", "Waiyaki Way", "Kangemi", "Westlands", "Kenyatta Ave",
                             "GPO", "ICEA", "Ragati Rd", "Hospital Rd", "KNH"),
        "return": _stages("Green park", "Haile Sellasie Ave", "Moi Ave", "Nkurumah Ave", "Jevanjee"),
    },
    {
        "brn_serial": "17", "start": "Kinoo", "end": "South B",
        "corridor": "Waiyaki Way OR Lower Kabete Rd.",
        "outbound": _stages("Kinoo", "Waiyaki Way", "Kangemi", "Westlands", "Kenyatta Ave", "GPO",
                             "ICEA", "Govt. Printers", "South B"),
        "return": _stages("Haile Sellasie Ave", "Moi Ave", "Govt. Printers", "Bunyala Rd", "Mater Hospital"),
    },
    {
        "brn_serial": "18", "start": "Kitengela", "end": "Westlands loop",
        "corridor": "Mombasa Road",
        "outbound": _stages("Kitengela", "Mombasa Rd", "Cabanas", "GM", "Nyayo Stadium", "Uhuru Highway",
                             "Uhuru Park", "St Paul's Church", "Museum Hill", "Ojijo", "Parklands",
                             "Westlands Triangle"),
        "return": _stages("KBC", "Uhuru Highway", "Parliament stage"),
    },
    {
        "brn_serial": "18A", "start": "Athi River", "end": "Westlands loop",
        "corridor": "Mombasa Road",
        "outbound": _stages("Athi River", "Mombasa Rd", "Mlolongo", "Cabanas", "Expressway", "Museum Hill",
                             "Uhuru Highway", "Ojijo", "Parklands", "Westlands Triangle"),
        "return": _stages("Express way"),
    },
    {
        "brn_serial": "19", "start": "Kitengela", "end": "Ruiru",
        "corridor": None,
        "outbound": _stages("Kitengela", "Nairobi-Namanga Rd", "Mombasa Rd", "Mlolongo", "Cabanas",
                             "Airport North Rd", "Taj mall", "Outering Rd", "Alsops", "Thika Rd",
                             "Kasarani", "Githurai", "Ruiru"),
        "return": _stages("Orbital"),
    },
    {
        "brn_serial": "19A", "start": "Kitengela", "end": "Thika",
        "corridor": None,
        "outbound": _stages("Kitengela", "Nairobi-Namanga Rd", "Mombasa Rd", "Mlolongo", "Cabanas",
                             "Airport North Rd", "Taj mall", "Outering Rd", "Eastern by pass", "Utawala",
                             "Kangundo Rd Junction", "Thika Rd", "Ruiru", "Juja", "Thika"),
        "return": _stages("Orbital"),
    },
    {
        "brn_serial": "20", "start": "Komarock-Donholm", "end": "Adams Jamhuri Estate",
        "corridor": "Ngong Road",
        "outbound": _stages("Spine Rd", "Savanna", "Jacaranda", "Green field", "Donholm", "Jogoo Rd",
                             "City Stadium", "Landhies Rd", "Haile Sellasie Ave", "Moi Ave", "Kenyatta Ave",
                             "GPO", "Ngong Rd", "Community", "Suna Rd", "Joseph Kangethe Rd", "Woodley",
                             "Kibera station Rd"),
        "return": _stages("GPO", "Ambassadeur", "Moi Ave", "Kimathi St", "Kenyatta Ave", "GPO", "Ngong Rd",
                           "Community", "KMTC"),
    },
    {
        "brn_serial": '21', "start": 'Lucky Summer', "end": 'Kibera - Ayany',
        "corridor": None,
        "outbound": _stages('Baba Dogo Rd', 'Thika Rd', 'Allsops', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Old Posta', 'Cabral St', 'Kenyatta Ave', 'GPO', 'Serena', 'Ngong Rd', 'KMTC', 'Ring Rd Kilimani', 'Kibera Drive'),
        "return": _stages('GPO', 'Kenyatta Ave', 'Mondlane St', 'Old Posta', "Murang'a Rd"),
    },
    {
        "brn_serial": '22', "start": 'Mathare North NYSEI', "end": 'Kangemi',
        "corridor": None,
        "outbound": _stages('Mathare North Rd', 'Redeemed Church', 'Juja Rd', 'MAB', "St. Teresa's Church", 'Kariokor Mkt', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'S-Lane Nkrumah Ave', 'Jeevanjee', 'University Way', "St. Paul's Church", 'Waiyaki Way', 'Chiromo', 'Westlands', 'ABC', 'Waruku'),
        "return": _stages('GPO', 'Ambassadeur', 'Moi Ave', 'Haile Selassie', 'KPCU', 'Athusi', 'Kariokor Mkt'),
    },
    {
        "brn_serial": '23', "start": 'Ngong', "end": 'Jericho',
        "corridor": None,
        "outbound": _stages('Ngong Rd', 'Karen', 'Racecourse', 'Junction Mall', 'Adams', 'Prestige Mall', 'KMTC', 'Maktaba Kuu', 'Haile Selassie Ave', 'Green Park', 'Agip', 'KPCU', 'Landhies Rd', 'Jogoo Rd', 'City Stadium', 'Nyasa Rd', 'Maringo', 'Jericho', 'Rabai Rd', 'Nile Rd'),
        "return": _stages('Landhies', 'Haile Selassie', 'KPCU', 'Green Park'),
    },
    {
        "brn_serial": '24', "start": 'Ngong', "end": 'Baba Dogo',
        "corridor": None,
        "outbound": _stages('Ngong Rd', 'Karen', 'Racecourse', 'Junction Mall', 'Adams', 'Prestige Mall', 'KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'ICEA', 'Ambassadeur', 'Ronald Ngala St', 'Racecourse Rd', 'Kariokor Mkt', 'Park Rd', 'Pangani', 'Thika Rd', 'Allsops', 'Baba Dogo Rd'),
        "return": _stages('Race Course', 'St Peters Clavers', 'Uyoma St', 'Tusker', 'Kencom'),
    },
    {
        "brn_serial": '25', "start": 'Ongata Rongai', "end": 'Baba Dogo',
        "corridor": None,
        "outbound": _stages('Magadi Rd', 'Bomas', 'Langata Rd', 'Wilson Airport', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'KPCU', 'Athusi', 'Kariokor Mkt', 'Thika Rd', 'Allsops', 'Baba Dogo Rd'),
        "return": _stages('Kamukunji', 'KPCU', 'Haile Selassie Ave'),
    },
    {
        "brn_serial": '26', "start": 'Ongata Rongai', "end": 'Westlands',
        "corridor": None,
        "outbound": _stages('Magadi Rd', 'Bomas', 'Langata Rd', 'Kungu Karumba Rd', 'Kibera', 'Ring Rd Kilimani', 'Yaya', 'Likoni Rd', 'Oloitoktok Rd', 'Ring Rd Kileleshwa', 'Riverside', 'Ring Rd Westlands'),
        "return": [],
    },
    {
        "brn_serial": '27', "start": "Otiende - St. Mary's", "end": 'Embakasi',
        "corridor": None,
        "outbound": _stages('Kungu Karumba', 'Langata Rd', 'Wilson Airport', 'Mbagathi Way', 'Ngong Rd', 'KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'ICEA', 'Ambassadeur', 'Ronald Ngala St', 'OTC', 'Landhies Rd', 'Jogoo Rd', 'City Stadium', 'Makadara', 'Donholm', 'Outering Rd', 'Taj Mall', 'Airport North Rd', 'Embakasi Rd'),
        "return": _stages('Landhies', 'St. Peter Clavers', 'Uyoma', 'Tusker', 'Kencom', 'Kimathi St', 'GPO'),
    },
    {
        "brn_serial": '27A', "start": 'Otiende - Southlands', "end": 'Embakasi',
        "corridor": None,
        "outbound": _stages('Kungu Karumba', 'Kitengela Rd', 'Southlands', 'Langata Rd', 'Wilson Airport', 'Mbagathi Way', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'KPCU', 'Landhies Rd', 'Jogoo Rd', 'City Stadium', 'Makadara', 'Donholm', 'Outering Rd', 'Taj Mall', 'Airport North Rd', 'Embakasi Rd'),
        "return": _stages('Landhies', 'KPCU', 'Govt Printers'),
    },
    {
        "brn_serial": '28', "start": 'Outer Ring - Buruburu', "end": 'Ngumo',
        "corridor": None,
        "outbound": _stages('Mumias South Rd', 'Rabai Rd', 'Uhuru Estate', 'Wangu Ave', 'Heshima Ave', '1st Ave', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'St. Peter Clavers Church', 'Uyoma St', 'Tusker', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'KMTC', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": _stages('GPO', 'Ambassadeur', 'Ronald Ngala', 'OTC'),
    },
    {
        "brn_serial": '29', "start": 'Pipeline', "end": 'Ngumo',
        "corridor": None,
        "outbound": _stages('Outering Rd', 'Taj Mall', 'Cabanas', 'Mombasa Rd', 'Bellevue', 'Nyayo Stadium', 'Haile Selassie Ave', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'KMTC', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": _stages('GPO', 'Ambassadeur', 'Gill House', 'Haile Selassie'),
    },
    {
        "brn_serial": '30', "start": 'Pipeline', "end": 'Kangemi',
        "corridor": None,
        "outbound": _stages('Outering Rd', 'Donholm', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'S-Lane Nkrumah Ave', 'Jeevanjee', 'University Way', 'Uhuru Hwy', "St. Paul's", 'Waiyaki Way', 'Chiromo', 'Westlands', 'ABC', 'Waruku'),
        "return": _stages('GPO', 'Ambassadeur', 'Gill House', 'Haile Selassie'),
    },
    {
        "brn_serial": '30A', "start": 'Pipeline', "end": 'KNH - Ngumo',
        "corridor": None,
        "outbound": _stages('Outering Rd', 'Lunga Lunga Rd', 'Enterprise Rd', 'Lusaka Rd', 'Bunyala Rd', 'Elgon Rd', 'Hospital Rd', 'KNH', 'Ngong Rd', 'KMTC', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": [],
    },
    {
        "brn_serial": '31', "start": 'Riruta Satellite', "end": 'Outering',
        "corridor": None,
        "outbound": _stages('Kinyanjui Rd', 'Wanyee Rd', 'Ngong Rd', 'Junction Mall', 'Adams', 'Prestige Mall', 'KMTC', 'Maktaba Kuu', 'Green Park', 'Haile Selassie Ave', 'Agip', 'KPCU', 'Pumwani Rd', 'Gikomba', 'Digo Rd', 'Lamu Rd', 'Ahero Rd', 'Ambira Rd', 'Heshima Ave', 'Wangu Ave', 'Buruburu Rd', 'Rabai Rd', 'Mumias South Rd'),
        "return": _stages('Haile Selassie', 'KPCU', 'Green Park'),
    },
    {
        "brn_serial": '32', "start": 'Riruta Satellite - Kabiria', "end": 'Kariobangi',
        "corridor": None,
        "outbound": _stages('Kinyanjui Rd', 'Wanyee Rd', 'Naivasha Rd', 'Junction Mall', 'Ngong Rd', 'Adams', 'Prestige Mall', 'KMTC', 'Community', 'Serena', 'Kenyatta Ave', 'GPO', 'ICEA', 'Ambassadeur', 'Ronald Ngala St', 'Racecourse Rd', 'Kariokor Mkt', 'Juja Rd', "St. Teresa's Church", 'Huruma Rd', 'Kariobangi Roundabout', 'Outering Rd', 'Kamunde Rd'),
        "return": _stages('Race Course', 'St. Peters Clavers', 'Uyoma', 'Tusker', 'Kencom'),
    },
    {
        "brn_serial": '33', "start": 'Kamulu', "end": 'Ngumo',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Ruai', 'Outering Rd', 'Donholm', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'Govt Printers', 'Green Park', 'Ngong Rd', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": _stages('Green Park', 'Haile Selassie', 'KPCU'),
    },
    {
        "brn_serial": '33A', "start": 'Kamulu', "end": 'Ngumo',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Ruai', 'Outering Rd', 'Kariobangi Roundabout', 'Juja Rd', 'Huruma', "St. Teresa's Church", 'Kariokor Mkt', 'Racecourse Rd', 'St. Peters Clavers Church', 'Uyoma St', 'Tusker', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'KMTC', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": _stages('GPO', 'Ambassadeur', 'Ronald Ngala', 'Racecourse'),
    },
    {
        "brn_serial": '34', "start": 'Ruaka', "end": 'Upper Hill / KNH',
        "corridor": None,
        "outbound": _stages('Limuru Rd', 'Village Market Mall', 'Muthaiga Mkt', 'Parklands', 'Ngara', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Old Posta', 'Cabral St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'Ragati Rd', 'Mara Rd', 'Elgon Rd', 'Hospital Rd'),
        "return": _stages('GPO', 'Kenyatta Ave', 'Mondlane St', 'Old Posta', "Murang'a Rd"),
    },
    {
        "brn_serial": '35', "start": 'Ruiru', "end": 'Upper Hill / KNH',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'Githurai', 'Allsops', 'Muthaiga', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Old Posta', 'Cabral St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'Ragati Rd', 'Mara Rd', 'Elgon Rd', 'Hospital Rd'),
        "return": _stages('GPO', 'Kenyatta Ave', 'Mondlane St', 'Old Posta', "Murang'a Rd"),
    },
    {
        "brn_serial": '36', "start": 'Umoja', "end": 'Kibera - Ayany',
        "corridor": None,
        "outbound": _stages('Loop anticlockwise via Outering / Manyanja Rd', 'Donholm', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'City Hall Way', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'KMTC', 'Ring Rd Kilimani', 'Kibera Drive'),
        "return": _stages('GPO', 'Ambassadeur', 'Moi Ave', 'Haile Selassie', 'KPCU', 'Athusi', 'Kariokor'),
    },
    {
        "brn_serial": '36A', "start": 'Umoja', "end": 'Kibera - Ayany Via Ind. Area',
        "corridor": None,
        "outbound": _stages('Loop anticlockwise via Outering / Manyanja Rd', 'Donholm', 'Lunga Lunga Rd', 'Enterprise Rd', 'Lusaka Rd', 'Bunyala Rd', 'Elgon Rd', 'Hospital Rd', 'KNH', 'Ngong Rd', 'KMTC', 'Ring Rd Kilimani', 'Kibera Drive'),
        "return": [],
    },
    {
        "brn_serial": '37', "start": 'Utawala - Githunguri', "end": 'Kangemi',
        "corridor": None,
        "outbound": _stages('Kinka', 'Benedicta', 'Eastern Bypass', 'Airport North Rd', 'Mombasa Rd', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Moi Ave', 'S-Lane Nkrumah Ave', 'Jeevanjee', 'University Way', 'Uhuru Hwy', "St. Paul's Church", 'Waiyaki Way', 'Chiromo', 'Westlands', 'ABC', 'Waruku'),
        "return": _stages('GPO', 'Ambassadeur', 'Gill House', 'Haile Selassie'),
    },
    {
        "brn_serial": '38', "start": 'Utawala - Airways', "end": 'Kangemi',
        "corridor": None,
        "outbound": _stages('MCA', 'Kinka', 'Benedicta', 'Eastern Bypass', 'Airport North Rd', 'Mombasa Rd', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Moi Ave', 'S-Lane Nkrumah Ave', 'Jeevanjee', 'University Way', 'Uhuru Hwy', "St. Paul's Church", 'Waiyaki Way', 'Chiromo', 'Westlands', 'ABC', 'Waruku'),
        "return": _stages('GPO', 'Ambassadeur', 'Gill House', 'Haile Selassie'),
    },
    {
        "brn_serial": '39', "start": 'Wangige - Lower Kabete', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Western Bypass', "King'eero", 'Lower Kabete Rd', 'Sarit', 'Westlands Triangle', 'Parklands Rd', 'Ojijo Rd', 'Kipande Rd', 'Old Posta', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tusker', 'Tom Mboya', 'Old Posta'),
    },
    {
        "brn_serial": '39A', "start": 'Wangige - Mwimuto', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Getathuru Rd', 'Mwimuto', 'Ngecha Rd', 'Lower Kabete Rd', 'Sarit', 'Westlands Triangle', 'Parklands Rd', 'Ojijo', 'Kipande Rd', 'Old Posta', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tusker', 'Tom Mboya', 'Old Posta'),
    },
    {
        "brn_serial": '40', "start": 'Thika - Makongeni', "end": 'Westlands Loop',
        "corridor": None,
        "outbound": _stages('Garissa Rd', 'Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Wangari Maathai Rd', 'Ojijo Rd', 'Parklands Rd', 'Ring Rd Parklands', 'Waiyaki Way (Return via Museum)'),
        "return": [],
    },
    {
        "brn_serial": '41', "start": 'Githurai', "end": 'South C',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'TRM Mall', 'Allsops', 'Outering Rd', 'Kariobangi Roundabout', 'Juja Rd', "St. Teresa's Church", '1st Ave Eastleigh', 'Muinami St', 'Digo Rd', 'Pumwani Rd', 'St. Peter Clavers Church', 'Tusker', 'Moi Ave', 'Haile Selassie Ave', 'KPCU', 'Govt Printers', 'Uhuru Hwy', 'Mombasa Rd', 'Popo Rd', 'Muhoho Ave', 'Ole Shapara Ave', 'Kiganjo Ave'),
        "return": _stages('Uhuru Hwy', 'Haile Selassie', 'Agip', 'KPCU', 'Retail', 'Pumwani Rd'),
    },
    {
        "brn_serial": '42', "start": 'Riruta Satellite', "end": 'Kahawa West',
        "corridor": None,
        "outbound": _stages('Kinyanjui Rd', 'Naivasha Rd', 'Ngong Rd', 'Junction Mall', 'Adams', 'Prestige Mall', 'Adams KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'ICEA', 'Moi Ave', 'Gill House', 'KPCU', 'Athusi', 'Park Rd', 'Pangani', 'Thika Rd', 'Roysambu', 'Kamiti Rd'),
        "return": _stages('Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'KPCU', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd'),
    },
    {
        "brn_serial": '43', "start": 'Gatina - Lavington', "end": 'Outering Rd Estate',
        "corridor": None,
        "outbound": _stages('Chalbi Dr', 'Isaac Gathanju Rd', 'James Gichuru Rd', 'Riverside Dr', 'Chiromo', 'Waiyaki Way', 'Uhuru Hwy', 'University Way', 'Slip Rd', 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'OTC', 'Landhies Rd', 'City Stadium', 'Jogoo Rd', 'Rabai Rd', 'Mumias South Rd'),
        "return": _stages('Landhies', 'St Peter Clavers', 'Uyoma', 'Tusker', 'Commercial', 'Slip Rd', 'University Way', 'Uhuru Hwy', 'Waiyaki Way'),
    },
    {
        "brn_serial": '44', "start": 'Kanungaga - Kileleshwa', "end": 'Komarock Estate',
        "corridor": None,
        "outbound": _stages('Macharia Rd', 'Gitanga Rd', 'Othaya Rd', 'Nyeri Rd', 'Gatundu Rd', 'Mandera Rd', 'Ring Rd Kileleshwa', 'Riverside Dr', 'Waiyaki Way', 'Uhuru Hwy', 'University Way', 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'OTC', 'Landhies Rd', 'City Stadium', 'Jogoo Rd', 'Donholm', 'Green Field', 'Jacaranda', 'Spine Rd'),
        "return": _stages('Landhies', 'St Peter Clavers', 'Uyoma', 'Tusker', 'Commercial', 'Slip Rd', 'University Way', 'Uhuru Hwy', 'Waiyaki Way'),
    },
    {
        "brn_serial": '45', "start": 'Gatina - Lavington', "end": 'South C',
        "corridor": None,
        "outbound": _stages('Chalbi Dr', 'Isaac Gathanju Rd', 'James Gichuru Rd', 'Riverside Dr', 'Chiromo', 'Waiyaki Way', 'Uhuru Hwy', 'Museum', 'Kipande Rd', 'Globe RA', 'Tom Mboya St', 'Cabral St', 'Moi Ave', 'Gill House', 'Govt Printers', 'Uhuru Hwy', 'Mombasa Rd', 'Popo Rd', 'Muhoho Ave', 'Ole Shapara Ave', 'Kiganjo Ave'),
        "return": _stages('Haile Selassie', 'Agip', 'Tom Mboya', 'Commercial', 'Globe RA', 'Kipande Rd', 'Museum', 'Waiyaki Way'),
    },
    {
        "brn_serial": '46', "start": 'Kanungaga - Kileleshwa', "end": 'Huruma Estate',
        "corridor": None,
        "outbound": _stages('Macharia Rd', 'Gitanga Rd', 'Othaya Rd', 'Nyeri Rd', 'Gatundu Rd', 'Mandera Rd', 'Ring Rd Kileleshwa', 'Riverside Dr', 'Waiyaki Way', 'Uhuru Hwy', 'Kipande Rd', 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'Riverside', 'Kariokor Mkt', 'Juja Rd', "St. Teresa's", 'Mathare Rd'),
        "return": _stages('Kariokor', 'Racecourse Rd', 'St Peters Clavers', 'Uyoma', 'Ronald Ngala', 'Tom Mboya', 'Commercial', 'Globe RA', 'Kipande Rd', 'Museum', 'Uhuru Hwy', 'Waiyaki Way'),
    },
    {
        "brn_serial": '47', "start": 'Umoja', "end": 'Highridge - Deep Sea',
        "corridor": None,
        "outbound": _stages('Moi Drive (loop clockwise)', 'Kangundo Rd', 'Outering Rd', 'Mumias South Rd', 'Buruburu', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies Rd', 'St Peter Clavers Church', 'Uyoma St', 'Tusker', 'Tom Mboya St', 'Globe RA', "Murang'a Rd", 'Limuru Rd', '3rd Parklands Ave', 'Mpaka Rd', 'Deep Sea', '6th Parklands Ave'),
        "return": _stages("Murang'a Rd", 'Globe RA', 'Tom Mboya', 'Ronald Ngala', 'OTC', 'Landhies Rd'),
    },
    {
        "brn_serial": '48', "start": 'Umoja', "end": 'Community - Green Park',
        "corridor": None,
        "outbound": _stages('Moi Drive (loop clockwise)', 'Kangundo Rd', 'Mumias South Rd', 'Rabai Rd', 'Wangu Ave', 'Heshima Ave', '1st Ave Eastleigh', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'Railway Club outside stop'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '49', "start": 'Kayole', "end": 'Uthiru Shops',
        "corridor": None,
        "outbound": _stages('Spine Rd (clockwise from Masimba)', 'Mayanja Rd', 'Donholm', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'City Hall Way', 'Kimathi St', 'GPO', 'Ngong Rd', 'Naivasha Rd', 'ILRI'),
        "return": _stages('GPO', 'Ambassadeur', 'Moi Ave', 'Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '49A', "start": 'Kayole', "end": 'Uthiru Shops',
        "corridor": None,
        "outbound": _stages('Spine Rd (clockwise from Masimba)', 'Mayanja Rd', 'Donholm', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Nkrumah Ave', 'Jeevanjee Gardens', 'University Way', 'Uhuru Hwy', 'Waiyaki Way', 'Westlands', 'Kangemi', 'Kabete Technical College', 'ILRI'),
        "return": _stages('GPO', 'Ambassadeur', 'Moi Ave', 'Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '50', "start": 'Kayole', "end": 'Highridge - Deep Sea',
        "corridor": None,
        "outbound": _stages('Spine Rd (clockwise from Masimba)', 'Mayanja Rd', 'Donholm', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'St Peter Clavers', 'Uyoma St', 'Tusker', 'Tom Mboya St', 'Commercial', 'Globe RA', "Murang'a Rd", 'Limuru Rd', '6th Parklands Ave', 'Deep Sea', 'Mpaka Rd', '3rd Parklands Ave'),
        "return": _stages("Murang'a Rd", 'Globe RA', 'Tom Mboya', 'Ronald Ngala', 'OTC', 'Landhies Rd'),
    },
    {
        "brn_serial": '51', "start": 'Pipeline', "end": 'Community - Green Park',
        "corridor": None,
        "outbound": _stages('Taj Mall turning loop', 'Outering Rd', 'Donholm', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'Ngong Rd', 'Community', 'Green Park Bus Stop'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '52', "start": 'Komarock', "end": 'Highridge - Deep Sea',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Outering Rd', 'Juja Rd', 'Kariokor', 'Racecourse Rd', 'St Peter Clavers Church', 'Uyoma St', 'Tusker', 'Tom Mboya St', 'Commercial', 'Old Posta', 'Globe RA', "Murang'a Rd", 'Limuru Rd', '3rd Parklands Ave', 'Mpaka Rd', 'Deep Sea', '6th Parklands Ave'),
        "return": _stages("Murang'a Rd", 'Globe RA', 'Tom Mboya', 'Ronald Ngala', 'OTC', 'Landhies Rd'),
    },
    {
        "brn_serial": '53', "start": 'Dandora', "end": 'Ngumo',
        "corridor": None,
        "outbound": _stages('Komarock Rd', 'Kariobangi South', 'Mumias South Rd', 'Buruburu', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies Rd', 'St. Peter Clavers Church', 'Tusker', 'Moi Ave', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'KMTC', 'Mbagathi Way', 'Mbagathi Rd', 'Mtongwe Rd'),
        "return": _stages('GPO', 'Ambassadeur', 'Ronald Ngala', 'OTC'),
    },
    {
        "brn_serial": '54', "start": 'Dandora', "end": 'South C',
        "corridor": None,
        "outbound": _stages('Komarock Rd', 'Kariobangi Roundabout', 'Juja Rd', "St. Teresa's Church", 'Kariokor Mkt', 'Kamukunji', 'Haile Selassie Ave', 'Uhuru Hwy', 'Mombasa Rd', 'Popo Rd', 'Muhoho Ave', 'Ole Shapara Ave', 'Kiganjo Ave'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '55', "start": 'Kariobangi', "end": 'Madaraka',
        "corridor": None,
        "outbound": _stages('Kamunde Rd', 'Outering Rd', 'Kariobangi Roundabout', 'Juja Rd', 'Huruma', "St. Teresa's Church", 'Ring Rd Ngara', 'Kariokor Mkt', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Govt Printers', 'Uhuru Hwy', 'Langata Rd', 'Muthaiti Ave', 'Gandhi Ave', 'Ole Sangale Ave', 'Mbagathi Way', 'Langata Rd'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '56', "start": 'Kariobangi', "end": 'Community - Green Park',
        "corridor": None,
        "outbound": _stages('Kamunde Rd', 'Outering Rd', 'Kariobangi Roundabout', 'Juja Rd', 'Huruma', "St. Teresa's Church", '1st Ave Eastleigh', 'Gen. Waruingi St', 'Muinami St', 'Digo Rd', 'Gikomba', 'Retail Mkt', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'Railway Club outside stop'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '57', "start": 'Huruma', "end": 'South B',
        "corridor": None,
        "outbound": _stages('Mathare Rd', 'Juja Rd', "St. Teresa's Church", 'Ring Rd Ngara', 'Kariokor Mkt', 'Racecourse Rd', 'St Peter Clavers Church', 'Uyoma St', 'Tusker', 'Moi Ave', 'Gill House', 'Haile Selassie Ave', 'Govt Printers', 'Uhuru Hwy', 'Bunyala Rd', 'Dunga Rd', 'Mater Hospital', 'Hazina', 'South B Shopping Centre'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '58', "start": 'Njiru', "end": 'Community - Green Park',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Outering Rd', 'Donholm', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'Kimathi St', 'Kenyatta Ave', 'GPO', 'Ngong Rd', 'Community', 'Railway Club outside bus stop'),
        "return": _stages('Haile Selassie', 'KPCU', 'Landhies Rd'),
    },
    {
        "brn_serial": '59', "start": 'Kawangware 46', "end": 'Eastleigh Via Gikomba',
        "corridor": None,
        "outbound": _stages('Kawangware Rd', 'Gitanga Rd', 'James Gichuru Rd', 'Waiyaki Way', 'Westlands', 'Uhuru Hwy', 'University Way', 'Slip Rd', 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'OTC', 'Pumwani Rd', 'Digo Rd', 'Muinami St', 'Gen Waruingi St', '1st Ave Eastleigh (anticlockwise circular)'),
        "return": _stages('St Peters Clavers', 'Uyoma', 'Tusker', 'Commercial', 'Slip Rd', 'University Way'),
    },
    {
        "brn_serial": '59A', "start": 'Kawangware 46', "end": 'Eastleigh Via Kariokor',
        "corridor": None,
        "outbound": _stages('Kawangware Rd', 'Gitanga Rd', 'James Gichuru Rd', 'Waiyaki Way', 'Westlands', 'Uhuru Hwy', 'University Way', 'Slip Rd', 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'Race Course Rd', 'Ring Rd Ngara', 'Kariokor Mkt', 'Juja Rd', "St Teresa's Church", '1st Ave Eastleigh (clockwise circular)'),
        "return": _stages('Race Course', 'St Peters Clavers', 'Uyoma', 'Tusker', 'Commercial', 'Old Posta', 'Slip Rd', 'University Way'),
    },
    {
        "brn_serial": '62', "start": 'Mwiki - Kasarani', "end": 'Westlands Loop',
        "corridor": None,
        "outbound": _stages('Mwiki Rd', 'Thika Rd', 'TRM Mall', 'Allsops', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji Police', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Nkrumah Ave', 'Jeevanjee', 'University Way', 'Uhuru Hwy', 'Museum', 'Ojijo Rd', 'Parklands Rd', 'Ring Rd Parklands', 'Waiyaki Way'),
        "return": _stages('Uhuru Hwy', 'Kenyatta Ave', 'Gill House', 'Haile Selassie Ave', 'KPCU'),
    },
    {
        "brn_serial": '63', "start": 'South B', "end": 'Highridge - Deep Sea',
        "corridor": None,
        "outbound": _stages('Mater Hospital (clockwise loop)', 'Hazina', 'South B Shopping Centre', 'Dunga Rd', 'Bunyala Rd', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Tom Mboya St', 'Commercial', 'Old Posta', "Murang'a Rd", 'Limuru Rd', '6th Parklands Ave', 'Deep Sea', 'Mpaka Rd', '3rd Parklands Ave'),
        "return": _stages('Tom Mboya St', 'Cabral St', 'Moi Ave', 'Gill House', 'Haile Selassie Ave'),
    },
    {
        "brn_serial": '63A', "start": 'South B', "end": 'Highridge - Deep Sea',
        "corridor": None,
        "outbound": _stages('Mater Hospital (anticlockwise loop)', 'Hazina', 'South B Shopping Centre', 'Dunga Rd', 'Bunyala Rd', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Tom Mboya St', 'Commercial', 'Old Posta', "Murang'a Rd", 'Limuru Rd', '3rd Parklands Ave', 'Mpaka Rd', 'Deep Sea', '6th Parklands Ave'),
        "return": _stages('Tom Mboya St', 'Cabral St', 'Moi Ave', 'Gill House', 'Haile Selassie Ave'),
    },
    {
        "brn_serial": '64', "start": 'Dagoretti Centre - Karinde', "end": 'Bomas',
        "corridor": None,
        "outbound": _stages('Kikuyu Rd', 'Dagoretti Rd', 'Langata Rd', 'Langata South Rd', 'Bogani Rd', 'Colleges', 'Bomas'),
        "return": [],
    },
    {
        "brn_serial": '65', "start": 'Mathare North NYSEI', "end": 'Sameer Park / GM',
        "corridor": None,
        "outbound": _stages('Mathare North Rd', 'Redeemed Church', 'Juja Rd', 'MAB', '1st Ave Eastleigh', 'Jogoo Rd', 'Likoni Rd', 'Enterprise Rd', 'General Motors', 'Sameer Park'),
        "return": [],
    },
    {
        "brn_serial": '66', "start": 'Kikuyu Town', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Kikuyu Rd', 'Waithaka', 'Naivasha Rd', 'Kawangware', 'Ngong Rd', 'Junction Mall', 'Adams Arcade', 'Prestige Mall', 'KMTC', 'Community', 'Serena', 'Kenyatta Ave', 'GPO', 'Ambassadeur', 'Tom Mboya', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave'),
    },
    {
        "brn_serial": '67', "start": 'Kikuyu Town', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Kikuyu Rd', 'Gitaru', 'A104', 'Waiyaki Way', 'Kangemi', 'Westlands', 'Uhuru Hwy', 'University Slip Rd', 'Globe Roundabout', 'Tom Mboya St', 'Hakati Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave'),
    },
    {
        "brn_serial": '68', "start": 'Ruiru', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'Githurai', 'Allsops', 'Muthaiga', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Old Posta', 'Tom Mboya', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tusker', 'Tom Mboya', 'Old Posta'),
    },
    {
        "brn_serial": '69', "start": 'Kitengela', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Nairobi-Namanga Rd', 'Mombasa Rd', 'Mlolongo', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'Haile Selassie Ave', 'Govt Printers'),
    },
    {
        "brn_serial": '70', "start": 'Athi River', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Nairobi-Namanga Rd', 'Mombasa Rd', 'Mlolongo', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'Haile Selassie Ave', 'Govt Printers'),
    },
    {
        "brn_serial": '71', "start": 'Kiserian - Ngong', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Ngong Rd', 'Matasia', 'Ngong', 'Karen', 'Racecourse', 'Junction Mall', 'Adams', 'Prestige Mall', 'KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'ICEA', 'Ambassadeur', 'Moi Ave', 'Haile Selassie Ave', 'Mfangano St', 'Hakati Rd', 'Temple'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'City Hall Way', 'Kencom', 'Kimathi St', 'Kenyatta Ave'),
    },
    {
        "brn_serial": '72', "start": 'Kiserian - Ongata Rongai', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Magadi Rd', 'Bomas', 'Langata Rd', 'Wilson Airport', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'Haile Selassie Ave', 'Govt Printers'),
    },
    {
        "brn_serial": '73', "start": 'Ongata Rongai - Gataka', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Rongai Tassia Supermarket (Magadi Rd)', 'Gataka Rd', 'Bogani Rd', 'Bomas', 'Langata', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Temple', 'Uyoma', 'Tusker', 'Moi Ave', 'Haile Selassie Ave', 'Govt Printers'),
    },
    {
        "brn_serial": '74', "start": 'Joska - Kamulu', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Ruai', 'Outering Rd', 'Juja Rd', 'MAB', "St. Teresa's Church", 'Pangani', 'Kariokor', 'Ring Rd Ngara', 'Haile Selassie Ave', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse', 'Ring Rd Ngara'),
    },
    {
        "brn_serial": '75', "start": 'Thika - Makongeni', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Garissa Rd', 'Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse Rd', 'Ring Rd Ngara'),
    },
    {
        "brn_serial": '76', "start": 'Gachie', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Redhill Rd (peak ext to Karura Kanyungu)', 'Limuru Rd', 'Muthaiga Mkt', 'Parklands', 'Ngara', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tusker', 'Tom Mboya', 'Old Posta'),
    },
    {
        "brn_serial": '76A', "start": 'Gichagi', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Redhill Rd', 'Westlands-Redhill Bypass', 'Waiyaki Way', 'ABC', 'Westlands Triangle', 'Parklands Police', 'Ojijo Rd', 'Kipande Rd', 'Globe RA', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tusker', 'Tom Mboya', 'Old Posta'),
    },
    {
        "brn_serial": '77', "start": 'Kiambu Town', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Kiambu Rd', 'Ridgeways', 'Thika Rd', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse Rd', 'Ring Rd Ngara'),
    },
    {
        "brn_serial": '78', "start": 'Mwiki - Kasarani', "end": 'Gikomba Market',
        "corridor": None,
        "outbound": _stages('Mwiki Rd', 'Kasarani', 'Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Ring Rd Ngara', 'Kariokor', 'Kinyanjui St', 'Digo Rd', 'Meru Rd', 'Gen. Waruingi St', 'Ring Rd Ngara'),
        "return": [],
    },
    {
        "brn_serial": '79', "start": 'Kiambu Town', "end": 'Gikomba Market',
        "corridor": None,
        "outbound": _stages('Kiambu Rd', 'Ridgeways', 'Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Ring Rd Ngara', 'Kariokor', 'Kinyanjui St', 'Digo Rd', 'Meru Rd', 'Gen. Waruingi St', 'Ring Rd Ngara'),
        "return": [],
    },
    {
        "brn_serial": '80', "start": 'Thika Town', "end": 'Gikomba Market',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Ring Rd Ngara', 'Kariokor', 'Kinyanjui St', 'Digo Rd', 'Meru Rd', 'Gen Waruingi St', 'Ring Rd Ngara'),
        "return": [],
    },
    {
        "brn_serial": '81', "start": 'Ruiru', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Thika Rd', "Murang'a Rd", 'Globe RA', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tom Mboya St', 'Globe Cinema'),
    },
    {
        "brn_serial": '82', "start": "Kenol - Murang'a", "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Meru-Nairobi Hwy', 'Thika Rd', 'Juja', 'Githurai', 'Allsops', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse Rd', 'Ring Rd Ngara'),
    },
    {
        "brn_serial": '83', "start": 'Limuru Town - Zambezi', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('A104', 'Gitaru', 'Uthiru Shops', 'ILRI', 'Naivasha Rd', 'Junction Shopping Mall', 'Ngong Rd', 'Kenyatta Ave', 'GPO', 'Kimathi St', 'Ambassadeur', 'Tom Mboya', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse Rd', 'Moi Ave', 'Kimathi St', 'Kenyatta Ave', 'GPO'),
    },
    {
        "brn_serial": '84', "start": 'Limuru Town - Kabuku', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Kiambu Rd', 'Kabuku', 'Ndenderu', 'Ruaka', 'Redhill Rd', 'Village Market', 'Limuru Rd', 'Parklands', "Murang'a Rd", 'Globe RA', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tom Mboya St', 'Globe Cinema'),
    },
    {
        "brn_serial": '85', "start": 'Nazareth - Banana Hill', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Raini', 'Banana Hill', 'Mucatha', 'Ruaka', 'Redhill Rd', 'Village Market', 'Limuru Rd', 'Parklands', "Murang'a Rd", 'Globe RA', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Tom Mboya St', 'Globe Cinema'),
    },
    {
        "brn_serial": '86', "start": 'Imara Daima - Inda', "end": 'Kangemi',
        "corridor": None,
        "outbound": _stages('Mombasa Rd', 'GM', 'Enterprise Rd', 'Lusaka Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Nkrumah Ave', 'Jeevanjee Gardens', 'University Way', 'Uhuru Hwy', 'Waiyaki Way', 'Muratha Rd'),
        "return": _stages('KBC', 'Uhuru Hwy', 'Kenyatta Ave', 'Kimathi St', 'Moi Ave', 'Gill House', 'Haile Selassie', 'Landhies'),
    },
    {
        "brn_serial": '87', "start": 'Githunguri Town', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('C65', 'Gathanje', 'Ikinu', 'Tinganga', 'Ndumberi', 'Kiambu Rd', 'Kiambu', 'Muthaiga', 'Thika Rd', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma', 'Ronald Ngala St', 'Racecourse Rd', 'Ring Rd Ngara'),
    },
    {
        "brn_serial": '88', "start": 'Lavington - Dennis Pritt', "end": 'Kahawa West',
        "corridor": None,
        "outbound": _stages('Mugumoini Rd', 'Lavington Primary', 'Olenguruone Rd', 'Likoni Rd', 'Dennis Pritt Rd', 'Milimani Rd', 'Kenyatta Ave', 'GPO', 'Mondlane', 'Tom Mboya', 'Globe', "Murang'a Rd", 'Thika Rd', 'Roysambu', 'Kamiti Rd'),
        "return": _stages("Murang'a Rd", 'Tom Mboya St', 'Old Posta', 'Cabral St', 'Kenyatta Ave', 'GPO'),
    },
    {
        "brn_serial": '89', "start": 'Katani Shopping Centre', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Katani Rd', 'Mombasa Rd', 'General Motors (GM)', 'Enterprise Rd', 'DT Dobie', 'Lusaka Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave RA', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma St', 'Ronald Ngala St', 'OTC', 'Landhies Rd'),
    },
    {
        "brn_serial": '89B', "start": 'Katani Shopping Centre', "end": 'Central Bus Station / Hakati',
        "corridor": None,
        "outbound": _stages('Katani Rd', 'Mombasa Rd', 'General Motors (GM)', 'Likoni Rd', 'Enterprise Rd', 'DT Dobie', 'Lusaka Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave RA', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": _stages('Uyoma St', 'Ronald Ngala St', 'OTC', 'Landhies Rd'),
    },
    {
        "brn_serial": '89C', "start": 'Katani Shopping Centre', "end": 'Westlands',
        "corridor": None,
        "outbound": _stages('Katani Rd', 'Mombasa Rd', 'Cabanas', 'Expressway - Museum Hill', 'Uhuru Hwy', 'Ojijo', 'Parklands Rd', 'Westlands Triangle', 'Ring Rd Parklands', 'Expressway'),
        "return": _stages('Expressway'),
    },
    {
        "brn_serial": '90', "start": 'Utawala', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Main Utawala Rd', 'Eastern Bypass', 'Airport North Rd', 'Mombasa Rd', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '91', "start": 'Kitengela', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Nairobi-Namanga Rd', 'Mombasa Rd', 'Mlolongo', 'Cabanas', 'GM', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '92', "start": 'Ongata Rongai', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Magadi Rd', 'Bomas', 'Langata Rd', 'Wilson Airport', 'Nyayo Stadium', 'Uhuru Hwy', 'Haile Selassie Ave', 'Agip', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '93', "start": 'Pipeline', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Taj Mall turning loop', 'Outering Rd', 'Donholm', 'Jogoo Rd', 'Makadara', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'Kencom', 'Simba St', 'Moi Ave', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '94', "start": 'Ngong Town', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Ngong Rd', 'Karen', 'Racecourse', 'Junction Mall', 'Adams', 'Prestige Mall', 'KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'Ambassadeur', 'Moi Ave', 'Haile Selassie Ave', 'Mfangano St', 'Hakati Rd', 'Temple'),
        "return": [],
    },
    {
        "brn_serial": '95', "start": 'Kikuyu - Waithaka', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Kikuyu Rd', 'Waithaka', 'Naivasha Rd', 'Kawangware', 'Ngong Rd', 'Junction Mall', 'Adams Arcade', 'Prestige Mall', 'KMTC', 'Community', 'Kenyatta Ave', 'GPO', 'Ambassadeur', 'Tom Mboya', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '96', "start": 'Umoja - Kayole - Komarock', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Moi Drv (Umoja 1 & 2)', 'Spine Rd', 'Mama Lucy Hospital', 'Komarock Estate entrance', 'Kayole loop (Masimba)', 'Mayanja Rd', 'Donholm', 'Jogoo Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave', 'City Hall Way', 'Simba St', 'Moi Ave', 'Ambassadeur', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '97', "start": 'Joska - Kamulu', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Kangundo Rd', 'Mama Lucy Hospital', 'Outering Rd', 'Juja Rd', 'MAB', '1st Ave Eastleigh', 'Muinami St', 'Digo Rd', 'Pumwani Rd', 'Haile Selassie Ave', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '98', "start": 'Pangani - Dandora', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Komarock Rd', 'Kariobangi Roundabout', 'Juja Rd', "St. Teresa's Church", 'Kariokor Mkt', 'Kamukunji', 'Haile Selassie Ave', 'Moi Ave RA', 'City Hall Way', 'Simba St', 'Moi Ave', 'Ambassadeur Hotel', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '99', "start": 'Ruaka - Banana', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Banana Laini Rd', 'Limuru Rd', 'Village Market Mall', 'Muthaiga Mkt', 'Parklands', 'Ngara', "Murang'a Rd", 'Globe Roundabout', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '100', "start": 'Kiambu - Ndumberi', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Kiambu Rd', 'Ridgeways', 'Thika Rd', 'Park Rd', 'Ring Rd Ngara', 'Kamukunji', 'Haile Selassie Ave', 'KPCU', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '101', "start": 'Kinoo - Waiyaki Way', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('A104', 'Uthiru', 'Waiyaki Way', 'Kangemi', 'Westlands', 'Uhuru Hwy', 'Kenyatta Ave', 'GPO', 'Kimathi St', 'Ambassadeur'),
        "return": [],
    },
    {
        "brn_serial": '102', "start": 'Thika Road - Ruiru', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'Park Rd', 'Ring Rd Ngara', 'Race Course Rd', 'Uyoma St', 'Ronald Ngala', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '103', "start": 'Thika Road - Kahawa West', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Thika Rd', "Murang'a Rd", 'Globe RA', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '104', "start": 'Thika Rd - Mwiki', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Thika Rd', 'Park Rd', 'Ring Rd Ngara', 'Race Course Rd', 'Uyoma St', 'Ronald Ngala', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '105', "start": 'Eastleigh - Gikomba', "end": 'Eastleigh Circular',
        "corridor": None,
        "outbound": _stages('1st Ave', 'Gen Waruingi', 'Muinami St', 'Digo Rd', 'Pumwani Rd', 'Racecourse Rd', 'St Peter Clavers Church', 'Uyoma St', 'Ronald Ngala St', 'Tom Mboya St', 'Commercial', 'Cabral St', 'Moi Ave', 'Mondlane St', 'Commercial', 'Ronald Ngala St', 'Race Course', 'Ring Rd Ngara', 'Park Rd', 'Juja Rd', "St. Teresa's Church"),
        "return": [],
    },
    {
        "brn_serial": '106', "start": 'Eastleigh - Gikomba', "end": 'Eastleigh Circular',
        "corridor": None,
        "outbound": _stages("St. Teresa's Church", 'Juja Rd', 'Park Rd', 'Ngara Rd', "Murang'a Rd", 'Globe RA', 'Tom Mboya St', 'Ronald Ngala St', 'OTC', 'Pumwani Rd', 'Digo Rd', 'Muinami St', 'Gen Waruingi St', '1st Ave Eastleigh'),
        "return": [],
    },
    {
        "brn_serial": '107', "start": 'Kibera', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Kibera Drive', 'Ring Rd Kilimani', 'Ngong Rd', 'Hospital Rd', 'Kenyatta Hospital', 'Ngong Rd', 'Kenyatta Ave', 'Kimathi St', 'Ambassadeur Hotel', 'Tom Mboya', 'Hakati Rd', 'Temple'),
        "return": [],
    },
    {
        "brn_serial": '108', "start": 'Kawangware 46', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Macharia Rd', 'Gitanga Rd', 'Valley Arcade', 'Argwings Kodhek Rd', 'Valley Rd', 'Kenyatta Ave', 'GPO', 'Kimathi St', 'Moi Ave', 'Ambassadeur Hotel', 'Tom Mboya St', 'Hakati Rd', 'Temple Rd'),
        "return": [],
    },
    {
        "brn_serial": '109', "start": 'Imara Daima - Inda', "end": 'Central Bus Stn / Hakati',
        "corridor": None,
        "outbound": _stages('Mombasa Rd', 'GM', 'Enterprise Rd', 'Lusaka Rd', 'City Stadium', 'Landhies Rd', 'Haile Selassie Ave', 'KPCU', 'Moi Ave Roundabout', 'Mfangano St', 'Hakati', 'Temple Rd'),
        "return": [],
    },]
