from typing import List, Dict

# Roles allowed to hold system-wide administrative power. Only accounts with
# one of these roles may be assigned to (or edited by someone assigned to)
# ADMIN/SUPERADMIN — enforced in routes/users.py, not just here.
ADMIN_TIER_ROLES = {"ADMIN", "SUPERADMIN"}

ROLE_MATRIX: Dict[str, List[str]] = {
    "SUPERADMIN": [
        "view_dashboard",
        "view_matatus",
        "edit_matatu_status",
        "view_routes",
        "manage_routes",
        "view_activity",
        "view_fines",
        "issue_fine",
        "update_fine_status",
        "view_users",
        "manage_users",
        "manage_admins",
        "update_booking_status",
        "view_reports",
        "review_report",
        "verify_saccos",
        "approve_license_renewal",
        "view_operator_verification",
        "decide_operator_verification_stage1",
        "decide_operator_verification_stage2",
        "remove_matatu",
        "record_crime",
        "view_enforcement_cases",
        "file_enforcement_case",
        "decide_enforcement_case",
        "manage_officer_assignments",
        "view_audit_logs",
        "view_system_health",
        "manage_system_config",
        "manage_crew",
        "manage_fare_stages",
    ],
    "ADMIN": [
        "view_dashboard",
        "view_matatus",
        "edit_matatu_status",
        "view_routes",
        "manage_routes",
        "view_activity",
        "view_fines",
        "issue_fine",
        "update_fine_status",
        "view_users",
        "manage_users",
        "update_booking_status",
        "view_reports",
        "review_report",
        "verify_saccos",
        "approve_license_renewal",
        "view_operator_verification",
        "decide_operator_verification_stage1",
        "decide_operator_verification_stage2",
        "remove_matatu",
        "record_crime",
        "view_enforcement_cases",
        "file_enforcement_case",
        "decide_enforcement_case",
        "manage_officer_assignments",
        "view_audit_logs",
        "manage_crew",
        "manage_fare_stages",
    ],
    "DIRECTOR_MOBILITY": [
        "view_dashboard",
        "view_operator_verification",
        "decide_operator_verification_stage1",
    ],
    "CHIEF_OFFICER": [
        "view_dashboard",
        "view_operator_verification",
        "decide_operator_verification_stage2",
    ],
    "ENFORCEMENT": [
        "view_dashboard",
        "view_matatus",
        "edit_matatu_status",
        "view_routes",
        "view_activity",
        "log_activity",
        "view_fines",
        "issue_fine",
        "view_reports",
        "review_report",
        "view_users",
        "record_crime",
    ],
    "ARRESTING_OFFICER": [
        "view_dashboard",
        "view_matatus",
        "view_routes",
        "view_activity",
        "log_activity",
        "file_enforcement_case",
        "view_enforcement_cases",
        "view_users",
        "view_reports",
    ],
    "RELEASING_OFFICER": [
        "view_dashboard",
        "view_matatus",
        "view_routes",
        "view_activity",
        "view_enforcement_cases",
        "decide_enforcement_case",
        "view_users",
        "view_reports",
    ],
    "ENFORCEMENT_COMMANDER": [
        "view_dashboard",
        "view_matatus",
        "view_routes",
        "view_activity",
        "view_enforcement_cases",
        "file_enforcement_case",
        "decide_enforcement_case",
        "manage_officer_assignments",
        "view_users",
        "view_reports",
        "review_report",
    ],
    "SACCO_OPERATOR": [
        "view_dashboard",
        "view_matatus",
        "add_matatu",
        "view_routes",
        "view_activity",
        "view_fines",
        "dispute_fine",
        "pay_fine",
        "submit_license_renewal",
        "manage_sacco_documents",
        "remove_matatu",
        "view_users",
        "manage_crew",
        "manage_fare_stages",
    ],
    "VIEWER": [
        "view_dashboard",
        "view_matatus",
        "view_routes",
        "view_activity",
        "view_fines",
        "view_users",
        "view_reports",
    ],
    "PASSENGER": [
        "view_matatus",
        "view_routes",
        "book_ticket",
        "view_own_bookings",
        "cancel_own_booking",
        "submit_report",
    ],
    "CREW": [
        "view_matatus",
        "view_routes",
        "manage_crew_seats",
        "view_matatu_bookings",
        "update_telemetry",
        "book_ticket",
        "update_booking_status",
        "log_activity",
        "view_reports",
    ],
}

def can(role: str, action: str) -> bool:
    return action in ROLE_MATRIX.get(role, [])
